#系统配置
myConfig:
  tokenOutTime: 30000
  verifyCodeOutTime: 3000
  idWorker:
    workerid: 1
    datacenterid: 1

#server配置
server:
  port: 8090
  servlet.context-path: /
  #servlet.session.timeout: 10
  stomcat.uri-encoding: UTF-8

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://82.157.171.87:3306/book
    username: linyuzhen
    password: linyuzhen
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

#mybatis配置，mappers.xml文件路径
mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: com.book.dao
  configLocation: classpath:mybatisConfig.xml
